base/urls.py
from django.conf.urls import url,include

from . import views
from django.views.generic import DetailView
from .models import LatestUpdates



urlpatterns = [
	
	
	 url(r'^$',views.index,name='index'),
	 url(r'^notice/(?P<pk>\d+)$',DetailView.as_view(model=LatestUpdates,template_name='base/update_detail.html')),
	 url(r'^accounts/',include('django.contrib.auth.urls')),
	 url(r'^accounts/profile/$',views.profile,name="profile"),
	 url(r'^student/(?P<pk>\d+)$', views.UserProfileDetailView.as_view(), name='student-detail'),                        
	
	url(r'^studentlist/(?P<type>[-\w+]+)/(?P<year>[-\w+]+)$', views.UserProfileListView.as_view(), name='student'),
	url(r'^accounts/profile/feedback$',views.FeedbackListView.as_view(),name="feedback"),
	url(r'^FeedbackDetail/create$', views.FeedbackCreateView.as_view(), name='create-feedback-detail'),

	url(r'^coures/$', views.Courses, name='courses'),
	url(r'^courselist/(?P<type>[-\w+]+)/(?P<year>[-\w+]+)$', views.CourseListView.as_view(), name='course-list'),
	url(r'^course/(?P<pk>\d+)$', views.CourseDetailView.as_view(), name='course-detail'),
	url(r'^tutorial/(?P<pk>\d+)/create/$', views.TutorialCreateView.as_view(), name='create-tutorial'),
	url(r'^lecnotes/(?P<pk>\d+)/create/$', views.LectureNotesCreateView.as_view(), name='create-lec-notes'),	
	url(r'^labassig/(?P<pk>\d+)/create/$', views.LabAssigCreateView.as_view(), name='create-lab-assig'),		
		
	url(r'^AcademicDetail/create$', views.AcademicDetailCreateView.as_view(), name='create-academic-detail'),
	url(r'^research/create$', views.ResearchCreateView.as_view(), name='create-research-detail'),
	url(r'^projects/create$', views.ProjectCreateView.as_view(), name='create-projects'),	 
	url(r'^experience/create$', views.ExperienceCreateView.as_view(), name='create-exp'),
	url(r'^accomp/create$', views.AccomplishmentsCreateView.as_view(), name='create-accomp'),	 
	url(r'^skill/create$', views.SkillsCreateView.as_view(), name='create-skill'),
	url(r'^contact/create$', views.ContactCreateView.as_view(), name='create-contact'),
			 

	url(r'^AcademicDetail/update/(?P<pk>\d+)$', views.AcademicDetailUpdate.as_view(), name='update'),
	url(r'^projects/update/(?P<pk>\d+)$', views.ProjectsUpdate.as_view(), name='update-projects'),
	url(r'^experience/update/(?P<pk>\d+)$', views.ExperienceUpdate.as_view(), name='update-exp'),
	url(r'^accomp/update/(?P<pk>\d+)$', views.AccomplishmentsUpdate.as_view(), name='update-accomp'),
	url(r'^skill/update/(?P<pk>\d+)$', views.SkillsUpdate.as_view(), name='update-skill'),
	url(r'^contact/update/(?P<pk>\d+)$', views.ContactUpdate.as_view(), name='update-contact'),
	url(r'^userprofile/update/(?P<pk>\d+)$', views.UserProfileUpdate.as_view(), name='update-profile'),
	

	url(r'^AcademicDetai/delete/(?P<pk>\d+)$', views.AcademicDetailDelete.as_view(), name='delete'),
	url(r'^projects/delete/(?P<pk>\d+)$', views.ProjectsDelete.as_view(), name='delete-projects'),
	url(r'^experience/delete/(?P<pk>\d+)$', views.ExperienceDelete.as_view(), name='delete-exp'),
	url(r'^accomp/delete/(?P<pk>\d+)$', views.AccomplishmentsDelete.as_view(), name='delete-accomp'),
	url(r'^skill/delete/(?P<pk>\d+)$', views.SkillsDelete.as_view(), name='delete-skill'),
	url(r'^contact/delete/(?P<pk>\d+)$', views.ContactDelete.as_view(), name='delete-contact'),

]

cse/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include('blog.urls')),
    url(r'^',include('base.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models

from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.urls import reverse
from datetime import datetime

# Create your models here.
class LatestUpdates(models.Model):
	heading=models.CharField(max_length=50)
	text=models.TextField()
	PRIORITY_CHOICES=(('imp','Very Important'),('reg','Regular'))
	
	priority=models.CharField(max_length=3,choices=PRIORITY_CHOICES)

	date=models.DateTimeField(null=True) 	
	

	def __str__(self):
		return str(self.heading)

from django.core.validators import MaxValueValidator, MinValueValidator
	
class UserProfile(models.Model):
	user=models.OneToOneField(User)
	first_name=models.CharField(max_length=100,default='')
	last_name=models.CharField(max_length=100,default='')
	desciption=models.CharField(max_length=500,default='')
	USER_TYPE_CHOICES=(('btec','B.TECH'),('mtec','M.TECH'),('tea','teacher'),('rst','Reaserch Student'))
	profile_image=models.FileField(null=True,blank=True)
	user_type=models.CharField(max_length=4,choices=USER_TYPE_CHOICES)
	USER_YEAR_CHOICES=(('1st','1st Year Student'),('2nd','2nd Year Student'),('3rd','Third Year Student'),('4th','4th Year Student'),('phd','PHD'),('fac','Faculty'))
	user_year=models.CharField(max_length=3,choices=USER_YEAR_CHOICES,default='1st')
	current_cgpa=models.FloatField(validators = [MinValueValidator(0), MaxValueValidator(10)],null=True)
	

	def __str__(self):
		return str(self.user.username)
	
	def get_absolute_url(self):
		return reverse('student-detail',args=[str(self.id)])

def create_profile(sender, **kwargs):
	if kwargs['created']:
		user_profile=UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile,sender=User)

class AcademicDetail(models.Model):
	user=models.ForeignKey(UserProfile,on_delete=models.SET_NULL,null=True)
	
	desciption=models.TextField(null=True)
	institute=models.TextField(null=True)
	
	percentage=models.TextField(null=True,blank=True)
	entering=models.DateField(null=True)
	leaving=models.DateField(null=True)

	def __str__(self):
		return str(self.user)
	def get_absolute_url(self):
		return reverse('profile')

class Projects(models.Model):
	user=models.ForeignKey(UserProfile,on_delete=models.SET_NULL,null=True)
	title=models.TextField()
	desciption=models.TextField(null=True)
	link=models.TextField(null=True,blank=True)
	
	
	start_date=models.DateField(null=True)
	end_date=models.DateField(null=True)

	def __str__(self):
		return str(self.user)
	def get_absolute_url(self):
		return reverse('profile')

class Experience(models.Model):
	user=models.ForeignKey(UserProfile,on_delete=models.SET_NULL,null=True)
	title=models.TextField()
	desciption=models.TextField(null=True)
	organisation=models.TextField()
	
	
	start_date=models.DateField(null=True)
	end_date=models.DateField(null=True)

	def __str__(self):
		return str(self.user)
	def get_absolute_url(self):
		return reverse('profile')

class Accomplishments(models.Model):
	user=models.ForeignKey(UserProfile,on_delete=models.SET_NULL,null=True)
	title=models.TextField()
	desciption=models.TextField(null=True,blank=True)
	
	
	
	def __str__(self):
		return str(self.user)
	def get_absolute_url(self):
		return reverse('profile')

class Skills(models.Model):
	user=models.ForeignKey(UserProfile,on_delete=models.SET_NULL,null=True)
	skill_name=models.TextField()

	def __str__(self):
		return str(self.user)
	def get_absolute_url(self):
		return reverse('profile')
class Contact(models.Model):
	user=models.ForeignKey(UserProfile,on_delete=models.SET_NULL,null=True)
	phone=models.PositiveIntegerField(blank=True)
	email_id=models.EmailField()

	def __str__(self):
		return str(self.user)

	def get_absolute_url(self):
		return reverse('profile')

class Course(models.Model):
	sub_code=models.CharField(max_length=50)
	sub_name=models.CharField(max_length=100)
	syllabus=models.TextField()
	COURSE_TYPE_CHOICES=(('btec','B.TECH'),('mtec','M.TECH'),('tea','teacher'),('rst','Reaserch Student'))
	user_type=models.CharField(max_length=4,choices=COURSE_TYPE_CHOICES)
	COURSE_YEAR_CHOICES=(('1st','1st Year Student'),('2nd','2nd Year Student'),('3rd','Third Year Student'),('4th','4th Year Student'))
	course_year=models.CharField(max_length=3,choices=COURSE_YEAR_CHOICES,default='1st')
	corse_cord=models.ForeignKey(User,on_delete=models.SET_NULL,null=True)

	def __str__(self):
		return str(self.sub_code)
	def get_absolute_url(self):
		return reverse('course-detail',args=[str(self.id)])

class Tutorial(models.Model):
	sub_code=models.ForeignKey(Course,on_delete=models.SET_NULL,null=True)
	
	tut_number=models.CharField(max_length=100)
	date=models.DateField()
	tut_file=models.FileField()
	def __str__(self):
		return str(self.sub_code)
	def get_absolute_url(self):
		return reverse('course-detail',args=[str(self.sub_code.id)])


class Lecture_notes(models.Model):
	sub_code=models.ForeignKey(Course,on_delete=models.SET_NULL,null=True)
	
	ppt_number=models.CharField(max_length=100)
	date=models.DateField()
	ppt_file=models.FileField()
	def __str__(self):
		return str(self.sub_code)
	def get_absolute_url(self):
		return reverse('course-detail',args=[str(self.sub_code.id)])

class Lab_Assignment(models.Model):
	sub_code=models.ForeignKey(Course,on_delete=models.SET_NULL,null=True)
	
	assig_number=models.CharField(max_length=100)
	date=models.DateField()
	assig_file=models.FileField()
	def __str__(self):
		return str(self.sub_code)
	def get_absolute_url(self):
		return reverse('course-detail',args=[str(self.sub_code.id)])

class Research_Paper(models.Model):
	author = models.ManyToManyField(User, limit_choices_to={'groups__name':"Faculty"})
	title=models.CharField(max_length=500)
	description=models.TextField()
	year=models.CharField(max_length=4)

	impact_factor=models.FloatField(validators = [MinValueValidator(0), MaxValueValidator(10)],null=True)
	link=models.TextField(null=True,blank=True)
	def __str__(self):
		return str(self.title)	

class Feedback(models.Model):
	q1_CHOICES=(('Yes','Yes'),('No','No'),('Sometimes','Sometimes'),('NA','NA'))
	q2_CHOICES=(('Fast','Fast'),('Perfect','Perfect'),('Slow','Slow'))
	Student=models.ForeignKey(User,on_delete=models.SET_NULL,null=True,related_name="feed_stu")
	Teacher=models.ForeignKey(User,on_delete=models.SET_NULL,null=True,limit_choices_to={'groups__name':"Faculty"})
	Presents_material_in_a_variety_of_ways=models.CharField(max_length=10,choices=q1_CHOICES,default='D')
	Planned_to_communicate_why_learning_this_is_important=models.CharField(max_length=10,choices=q1_CHOICES,default='D')
	The_information_was_presented_logically=models.CharField(max_length=10,choices=q1_CHOICES,default='D')
	How_is_the_pace_of_the_class=models.CharField(max_length=10,choices=q2_CHOICES,default='Slow')
	Were_notes_efficient_for_after_learning=models.CharField(max_length=10,choices=q1_CHOICES,default='NA')

	date=models.DateField(default=datetime.now,blank=True)
	comments=models.TextField(max_length=1000,blank=True)
	ifactor=models.IntegerField(default=6)
	def __str__(self):
		return str(self.Teacher)	
	
		




	
		
	





		

base/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from .models import *
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.db.models import Q



class AcademicDetailForm(forms.ModelForm):
    

	desciption=forms.CharField()
	institute=forms.CharField()
	percentage=forms.CharField()
	entering=forms.DateField(widget=forms.SelectDateWidget(years=range(1950,3000)))
	leaving=forms.DateField(widget=forms.SelectDateWidget(years=range(1950,3000)) 	)
	class Meta:
		model =  AcademicDetail
		fields = [
		"desciption",
		"institute",
		"percentage",
		"entering",
		"leaving",
	]
class ResearchDetailForm(forms.ModelForm):
    

	year=forms.CharField(label='Year : (please enter numeric four digit year only)')
	author = forms.CharField(widget=forms.Textarea, required=False)

	def clean_author(self):
		author_data = self.cleaned_data.get('author',None)
		author = []
        #here, a comma is used a delim, so it's not allowed in the tool name.
		for td in author_data.split(','): 
			t= User.objects.get_or_create(username=td)
			author.append(t)
			print(author)
			return author
	
	class Meta:
		model =  Research_Paper
		fields = [
		"author",
		"title",
		"description",
		"year",
		"impact_factor",
		"link"

	]

class ProjectsForm(forms.ModelForm):
    
	title=forms.CharField()
	desciption=forms.CharField()
	
	link=forms.CharField()
	start_date=forms.DateField(widget=forms.SelectDateWidget(years=range(1950,3000)))
	end_date=forms.DateField(widget=forms.SelectDateWidget(years=range(1950,3000)) 	)
	class Meta:
		model =  Projects
		fields = [
		"title",
		"desciption",
		"link",
		
		"start_date",
		"end_date",
	]

class ExperienceForm(forms.ModelForm):
    
	title=forms.CharField()
	desciption=forms.CharField()
	
	organisation=forms.CharField()
	start_date=forms.DateField(widget=forms.SelectDateWidget(years=range(1950,3000)))
	end_date=forms.DateField(widget=forms.SelectDateWidget(years=range(1950,3000)) 	)
	class Meta:
		model =  Experience
		fields = [
		"title",
		"desciption",
		"organisation",
		
		"start_date",
		"end_date",
	]

class AccomplishmentsForm(forms.ModelForm):
	helper = FormHelper()
	helper.form_tag = False
	title=forms.CharField()
	desciption=forms.CharField()
	
	
	class Meta:
		model =  Accomplishments
		fields = [
		"title",
		"desciption",
	]

class SkillsForm(forms.ModelForm):
	
	skill_name=forms.CharField()
	
	
	class Meta:
		model =Skills
		fields = [
		"skill_name",
		
	]

class ContactForm(forms.ModelForm):
	
	email_id=forms.CharField()
	phone=forms.CharField()
	
	
	class Meta:
		model =Contact
		fields = [
		"email_id","phone"
		
	]
	
class EditUserProfileForm(forms.ModelForm):
    class Meta:
        model=UserProfile
        fields=('first_name' , 'last_name', "desciption", "profile_image","user_year")

class TutorialForm(forms.ModelForm):
	date=forms.DateField(widget=forms.SelectDateWidget(years=range(1950,3000)))
	class Meta:
		model=Tutorial
		fields=('tut_number','tut_file','date')

class Lecture_notesForm(forms.ModelForm):
	date=forms.DateField(widget=forms.SelectDateWidget(years=range(1950,3000)))
	class Meta:
		model=Lecture_notes
		fields=('ppt_number','ppt_file','date')
		
class Lab_AssignmentForm(forms.ModelForm):
	date=forms.DateField(widget=forms.SelectDateWidget(years=range(1950,3000)))
	class Meta:
		model=Lab_Assignment
		fields=('assig_number','assig_file','date')

class FeedbackForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		self.user=kwargs.pop('user')
		super(FeedbackForm, self).__init__(*args, **kwargs)
		ls=list(self.user.groups.values_list('name',flat=True))
		criteria1=Q(groups__name=ls[0])
		
		self.fields['Teacher'] = forms.ModelChoiceField(queryset=User.objects.filter(criteria1).exclude(groups__name="Student"))
	class Meta:
		model=Feedback
		title="Feedback"
		fields=['Teacher',
		'comments',
		'Presents_material_in_a_variety_of_ways',
		'Planned_to_communicate_why_learning_this_is_important',
		'The_information_was_presented_logically',
		'How_is_the_pace_of_the_class',
		'Were_notes_efficient_for_after_learning'
		]
		
		

base/templates/base/corsemat_create_form.html
{%extends 'base/base_generic.html'%}
{%block content%}




	{{sub_code.id}}
	
	<p>{{sub_code.corse_cord}} is the cordinator of this course</p>
	{% if request.user.is_authenticated and  sub_code.corse_cord == request.user %}
	
	
	 <form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
   
{% for field in form%}
        	<div class="row">
        	<div class="col-sm-3">{{field.label}}</div>
        	<div class="col-sm-6" >{{field}}</div>
        	
        		
        	</div><br>
        {%endfor%}

 


    <center><button type="submit">Yup!Done</button></center>
</form>
	{%else%}
	<p>Oops! looks like you are not authorized to edit this course incase of dispute <br>please contact CITM lab</p>


	{%endif%}
	
{%endblock%}

base/templates/base/course.html
{% extends "base/base_generic.html" %}
{% block content %}

<p>BTECH</p>
<ol>
	<li><a class="dropdown-item"  href="/courselist/btec/1st">First Year</a></li>
</ol>
{%endblock%}

base/templates/base/course_detail.html
{%extends 'base/base_generic.html'%}
{%block content%}



<center><h3 style="font-weight: bold;">{{course.sub_name}} | {{course.sub_code}}</h3></center>
<hr>

<div class="row">
<div class="col-sm-4"></div>

<div class="col-sm-7">
<div id="accordion" role="tablist">
  <div class="card">
    <div class="card-header" role="tab" id="headingOne">
      <h5 class="mb-0">
        <a data-toggle="collapse" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Tutorials
        </a>
      </h5>
    </div>

    <div id="collapseOne" class="collapse" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion">
      <div class="card-body">
       {%for each in course.tutorial_set.all%}
		
     
		<h5><li><a class="badge badge-success" href="{{each.tut_file.url}}">{{each.tut_number}} | {{each.tut_file}}</a></li></h5>
		
			{%endfor%}</ul>

	<br>
	
	
	{% if request.user.is_authenticated and  course.corse_cord == request.user %}

	 <a href="{% url 'create-tutorial' course.id %}"> you can edit</a>
	

	{%endif%}
	



      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" role="tab" id="headingTwo">
      <h5 class="mb-0">
        <a class="collapsed" data-toggle="collapse" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Lecture Notes
        </a>
      </h5>
    </div>
    <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo" data-parent="#accordion">
      <div class="card-body">
        	  {%for each in course.lecture_notes_set.all%}
			<div class="row">
			<h5><li><a class="badge badge-success" href="{{each.ppt_file.url}}">{{each.ppt_number}} | {{each.ppt_file}}</a></li></h5>

			</div>
		{%endfor%}
    {% if request.user.is_authenticated and  course.corse_cord == request.user %}

   <a href="{% url 'create-lec-notes' course.id %}"> you can edit</a>
  

  {%endif%}
       
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" role="tab" id="headingThree">
      <h5 class="mb-0">
        <a class="collapsed" data-toggle="collapse" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Syllabus
        </a>
      </h5>
    </div>
    <div id="collapseThree" class="collapse" role="tabpanel" aria-labelledby="headingThree" data-parent="#accordion">
      <div class="card-body">
      <pre>{{course.syllabus}}</pre>
      
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" role="tab" id="headingFour">
      <h5 class="mb-0">
        <a class="collapsed" data-toggle="collapse" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
          Lab Assignments
        </a>
      </h5>
    </div>
    <div id="collapseFour" class="collapse" role="tabpanel" aria-labelledby="headingFour" data-parent="#accordion">
      <div class="card-body">
   {%for each in course.lab_assignment_set.all%}
		
     
		<h5><li><a class="badge badge-success" href="{{each.tut_file.url}}">{{each.assig_number}} | {{each.assig_file}}</a></li></h5>
		
			{%endfor%}</ul>

	<br>
	
    {% if request.user.is_authenticated and  course.corse_cord == request.user %}

   <a href="{% url 'create-lab-assig' course.id %}"> you can edit</a>
  

  {%endif%}

	
	
      
      </div>
    </div>
  </div>


</div>
</div>
</div>


{%endblock%}

base/templates/base/course_list.html
{% extends "base/base_generic.html" %}

{% block content %}
<br>

  {% if course_list %}
    <ul>

      {% for each in course_list %}
        
      <div class="row list-row">
       <div class="col-sm-2"> 
    </div>
        <div class="col-sm-5">
          
          <div class="container">
              <h4><b> <a href="{{ each.get_absolute_url }}" >{{ each.sub_code }}</a> </b></h4> 
                 
                 <p></p> 
          </div>
          <hr>
        </div>

      
     

     

              
      </div>
      {% endfor %}

    </ul>
    {% else %}
      <p>These are Super Cool Writers</p>
    {% endif %}       
{% endblock %}

base/templates/base/detaildelete_form.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

base/templates/base/userprofile_detail.html
{% extends "base/base_generic.html" %}
{% block headfile %}
{% endblock %}
{% block content %}

<div class="profile-detail-header container-fluid">

<div class="row">

<div class="col-sm-6" >
<h1 class="text-left"><b>{{userprofile.first_name}}&nbsp;{{userprofile.last_name}} </b></h1> 
<hr>
<p style="color: white;">{{userprofile.desciption}}</p>


</div>
<div class="col-sm-6">

{% if userprofile.profile_image%}
  <img class="rounded-circle" width="200px" height="200px"  src="{{userprofile.profile_image.url}}">
{%endif%}

  </div>
</div>



</div>
<div style="margin: 8px">
<div  id="1">

<div class="profile-detail-block-1">
  
    
    <div class="row profile-element">
    <div class="row profile-detail-heading">Academic Detail</div>

    <div class="col-sm-12">
     <ul>
          {% for academic_detail in userprofile.academicdetail_set.all %}
    
      
       <li>
     <h4 class="profile-detail-inst"><b>{{academic_detail.institute}}</b> </h4>
     <h6 style="font-style: italic; color: #999;"> {{academic_detail.entering}} - {{academic_detail.leaving}} </h6>
     <h5 style="color: #333;">{{academic_detail.desciption}}</h5>
     <b><h5>Percentage/Grade: </b>{{academic_detail.percentage}}</h5> 
     </li>
     {%endfor%}
      </ul>
      </div>
</div>
     

  
   
      
  
  </ol>
</div>
<div class="profile-detail-block-1">
  <div class="row profile-element">
    <div class="row profile-detail-heading">Projects</div>
    <div class="col-sm-12">
    <ul>
          {% for each in userprofile.projects_set.all %}
    
        <li>
            <h4 class="profile-detail-inst"><b><a href="//{{each.link}}">{{each.title}}</b> </a></h4>
             <h6 style="font-style: italic; color: #999;"> {{each.start_date}} - {{each.end_date}} </h6>
            <h5 style="color: #333;">{{each.desciption}}</h5>
     </li>
        {%endfor%}
   </ul>
   </div>
    </div>
</div>
<div class="profile-detail-block-1">
  <div class="row profile-element">
    <div class="row profile-detail-heading">Experience</div>
    <div class="col-sm-12">
    <ul>
          {% for each in userprofile.experience_set.all %}
    
        <li>
            <h4 class="profile-detail-inst"><b>{{each.title}}</b> </a></h4>
             <h6 style="font-style: italic; color: #999;"> {{each.start_date}} - {{each.end_date}} </h6>
             <h5 style="color: #333;">{{each.organisation}}</h5>
            <h5 style="color: #333;">{{each.desciption}}</h5>

     </li>
        {%endfor%}
   </ul>
   </div>
    </div>
</div>
<div class="profile-detail-block-1">
  <div class="row profile-element">
    <div class="row profile-detail-heading">Accomplishments</div>
    <div class="col-sm-12">
    <ul>
          {% for each in userprofile.accomplishments_set.all %}
    
        <li>
            <h4 class="profile-detail-inst"><b>{{each.title}}</b> </a></h4>
            
            
            <h5 style="color: #333;">{{each.desciption}}</h5>

     </li>
        {%endfor%}
   </ul>
   </div>
    </div>
</div>
<div class="profile-detail-block-1">
  <div class="row profile-element">
    <div class="row profile-detail-heading">Skills</div>
    <div class="col-sm-12">
    <ul>
          {% for each in userprofile.skills_set.all %}
    
        <li>
            
            
            <h5 style="color: #333;">{{each.skill_name}}</h5>

     </li>
        {%endfor%}
   </ul>
   </div>
    </div>
</div>


<div class="profile-detail-block-1">
  <div class="row profile-element">
    <div class="row profile-detail-heading">Research and Publications
    
    </div>
    <div class="col-sm-12">

    {% if userprofile.user.research_paper_set.all %}
   
    
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Year', 'Number of Publications'],
          {% for i in count_paper %}
          ['{{i.year}}', {{i.the_count}}],
          {%endfor%}
        ]);

        var options = {
          title: 'Year Wise Publications :  {{userprofile.first_name}} {{userprofile.last_name}}',
          curveType: 'function',
          legend: { position: 'bottom' }
        };

        var chart = new google.visualization.LineChart(document.getElementById('curve_chart'));

        chart.draw(data, options);
      }
    </script>
 
    <div id="curve_chart" style="width: 900px; height: 500px"></div>
  
    {% else %}
    <p>no publications yet.. </p>

    {% endif %}
    

    <ul>
          {% for each in userprofile.user.research_paper_set.all %}
       
        <li>
            
            
            <h5 style="color: #333;font-weight: bold;">{{each.title}}
          
            </h5>
            <p>Year Of Publication: {{ each.year}}</p>
            <p> Authors:{% for authors in each.author.all %}
              {{ authors.userprofile.first_name }} {{authors.userprofile.last_name}} |
              {% endfor %}</p>

              <p style="color: #333;font-weight: bold;" > Publication Journal/Conference :{{ each.description }}</p>

     </li>
     <hr>
        {%endfor%}
    </ul>
   </div>
    </div>
</div>


<div class="profile-detail-block-1">
  <div class="row profile-element">
    <div class="row profile-detail-heading">Contact Information</div>
    <div class="col-sm-12">
    <ul>
          {% for each in userprofile.contact_set.all %}
    
        <li>
            
            
            <h5 style="color: #333;">Phone :{{each.phone}}</h5>
            <h5 style="color: #333;">Email id:{{each.email_id}}</h5>

     </li>
        {%endfor%}
   </ul>
   </div>
    </div>
</div>








           
{% endblock %}